/**
 * Tradeshift Tasks
 * This is a sample for swagger-maven-plugin
 *
 * OpenAPI spec version: v1
 * Contact: jba@tradeshift.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;


/**
 * ExternalTaskDTO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-08T05:08:49.231Z")
public class ExternalTaskDTO   {
  @SerializedName("id")
  private String id = null;

  @SerializedName("handler")
  private String handler = null;

  @SerializedName("groupId")
  private String groupId = null;

  /**
   * Gets or Sets state
   */
  public enum StateEnum {
    @SerializedName("ASSIGNED")
    ASSIGNED("ASSIGNED"),
    
    @SerializedName("COMPLETED")
    COMPLETED("COMPLETED"),
    
    @SerializedName("DELETED")
    DELETED("DELETED");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("state")
  private StateEnum state = null;

  @SerializedName("createdOn")
  private DateTime createdOn = null;

  @SerializedName("subjectId")
  private String subjectId = null;

  @SerializedName("assigner")
  private String assigner = null;

  @SerializedName("assignedOn")
  private DateTime assignedOn = null;

  @SerializedName("completedBy")
  private String completedBy = null;

  @SerializedName("completedOn")
  private DateTime completedOn = null;

  @SerializedName("outcome")
  private String outcome = null;

  @SerializedName("assignees")
  private List<String> assignees = new ArrayList<String>();

  public ExternalTaskDTO id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ExternalTaskDTO handler(String handler) {
    this.handler = handler;
    return this;
  }

   /**
   * Get handler
   * @return handler
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getHandler() {
    return handler;
  }

  public void setHandler(String handler) {
    this.handler = handler;
  }

  public ExternalTaskDTO groupId(String groupId) {
    this.groupId = groupId;
    return this;
  }

   /**
   * Get groupId
   * @return groupId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGroupId() {
    return groupId;
  }

  public void setGroupId(String groupId) {
    this.groupId = groupId;
  }

  public ExternalTaskDTO state(StateEnum state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(example = "null", value = "")
  public StateEnum getState() {
    return state;
  }

  public void setState(StateEnum state) {
    this.state = state;
  }

  public ExternalTaskDTO createdOn(DateTime createdOn) {
    this.createdOn = createdOn;
    return this;
  }

   /**
   * Get createdOn
   * @return createdOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(DateTime createdOn) {
    this.createdOn = createdOn;
  }

  public ExternalTaskDTO subjectId(String subjectId) {
    this.subjectId = subjectId;
    return this;
  }

   /**
   * Get subjectId
   * @return subjectId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSubjectId() {
    return subjectId;
  }

  public void setSubjectId(String subjectId) {
    this.subjectId = subjectId;
  }

  public ExternalTaskDTO assigner(String assigner) {
    this.assigner = assigner;
    return this;
  }

   /**
   * Get assigner
   * @return assigner
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAssigner() {
    return assigner;
  }

  public void setAssigner(String assigner) {
    this.assigner = assigner;
  }

  public ExternalTaskDTO assignedOn(DateTime assignedOn) {
    this.assignedOn = assignedOn;
    return this;
  }

   /**
   * Get assignedOn
   * @return assignedOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getAssignedOn() {
    return assignedOn;
  }

  public void setAssignedOn(DateTime assignedOn) {
    this.assignedOn = assignedOn;
  }

  public ExternalTaskDTO completedBy(String completedBy) {
    this.completedBy = completedBy;
    return this;
  }

   /**
   * Get completedBy
   * @return completedBy
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCompletedBy() {
    return completedBy;
  }

  public void setCompletedBy(String completedBy) {
    this.completedBy = completedBy;
  }

  public ExternalTaskDTO completedOn(DateTime completedOn) {
    this.completedOn = completedOn;
    return this;
  }

   /**
   * Get completedOn
   * @return completedOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getCompletedOn() {
    return completedOn;
  }

  public void setCompletedOn(DateTime completedOn) {
    this.completedOn = completedOn;
  }

  public ExternalTaskDTO outcome(String outcome) {
    this.outcome = outcome;
    return this;
  }

   /**
   * Get outcome
   * @return outcome
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOutcome() {
    return outcome;
  }

  public void setOutcome(String outcome) {
    this.outcome = outcome;
  }

  public ExternalTaskDTO assignees(List<String> assignees) {
    this.assignees = assignees;
    return this;
  }

   /**
   * Get assignees
   * @return assignees
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getAssignees() {
    return assignees;
  }

  public void setAssignees(List<String> assignees) {
    this.assignees = assignees;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalTaskDTO externalTaskDTO = (ExternalTaskDTO) o;
    return Objects.equals(this.id, externalTaskDTO.id) &&
        Objects.equals(this.handler, externalTaskDTO.handler) &&
        Objects.equals(this.groupId, externalTaskDTO.groupId) &&
        Objects.equals(this.state, externalTaskDTO.state) &&
        Objects.equals(this.createdOn, externalTaskDTO.createdOn) &&
        Objects.equals(this.subjectId, externalTaskDTO.subjectId) &&
        Objects.equals(this.assigner, externalTaskDTO.assigner) &&
        Objects.equals(this.assignedOn, externalTaskDTO.assignedOn) &&
        Objects.equals(this.completedBy, externalTaskDTO.completedBy) &&
        Objects.equals(this.completedOn, externalTaskDTO.completedOn) &&
        Objects.equals(this.outcome, externalTaskDTO.outcome) &&
        Objects.equals(this.assignees, externalTaskDTO.assignees);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, handler, groupId, state, createdOn, subjectId, assigner, assignedOn, completedBy, completedOn, outcome, assignees);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalTaskDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    handler: ").append(toIndentedString(handler)).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    subjectId: ").append(toIndentedString(subjectId)).append("\n");
    sb.append("    assigner: ").append(toIndentedString(assigner)).append("\n");
    sb.append("    assignedOn: ").append(toIndentedString(assignedOn)).append("\n");
    sb.append("    completedBy: ").append(toIndentedString(completedBy)).append("\n");
    sb.append("    completedOn: ").append(toIndentedString(completedOn)).append("\n");
    sb.append("    outcome: ").append(toIndentedString(outcome)).append("\n");
    sb.append("    assignees: ").append(toIndentedString(assignees)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

